### ISSUE TITLE
There should be a standard (Page not found) message and also the icons should be removed from this page

### ISSUE THREAD

**Issue by Grgnavin** [code100x/job-board#177]
### 📜 Description

The media icons are in this page (should be removed) and the text 
404: This page could not be found.
This is also not visible..

![Page_not_Found](https://github.com/user-attachments/assets/9f0b7f52-d5e5-4816-b600-d7245574b1e1)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by pratikprajapati0708** [comment]
This is the issue due to the page background. If the mode becomes dark then it shows the 404 page

**Comment by Grgnavin** [comment]
What abt the icons?

**Comment by ppratik07** [comment]
#186 Fixed footer component.

I think this will fix your issue.  Meanwhile this is not a permanent fix as here we need to add the url's where we want the footer to be displayed . If you want to do it dynamically then we need to create a new custom 404 page for it and this will be a new FEATURE request in that case.

**Comment by VineeTagarwaL-code** [comment]
Yeah that does make sense to have a good 404 page

**Comment by ppratik07** [comment]
> Yeah that does make sense to have a good 404 page

Let me work on creating  a new custom one then

**Comment by ppratik07** [comment]
<img width="1470" alt="Screenshot 2024-08-15 at 9 37 18 PM" src="https://github.com/user-attachments/assets/a763dfa2-ff40-41d0-b240-a2884b71f9f6">
<img width="1470" alt="Screenshot 2024-08-15 at 9 38 00 PM" src="https://github.com/user-attachments/assets/e48ebc2c-0380-4e41-860a-1b188eb5c477">
<img width="1470" alt="Screenshot 2024-08-15 at 9 37 42 PM" src="https://github.com/user-attachments/assets/118bc8e6-8d0c-47b1-8c93-01a402ca441c">

I have not removed the icons since in some of the pages I have seen in industry level I can see the footer has been already attached to their pages. Let me know if they can be removed.
